# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jungwoo Shim
title: Graduate Student at Korea University
email: jshim0978@gmail.com
website: jshim0978.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: jshim0978
github_username: jshim0978
instagram_username: j_w_shim
linkedin_username: "Jungwoo Shim"

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Jungwoo Shim, and I am a graduate student at Korea University, specializing in Artificial Intelligence. My current research focuses on mitigating large language model hallucinations through plug-and-play prompt refinement. I have a solid foundation in computer science from Chungnam National University, and I am skilled in various programming languages and technologies including Python, Java, and frontend development. I am passionate about large language models and their applications in real-world scenarios.

content:
  - title: Publications # New section for publications
    layout: list
    content:
      - layout: top-middle
        title: CPR - Mitigating Large Language Model Hallucinations with Curative Prompt Refinement
        sub_title: Published in IEEE International Conference on Systems, Man, and Cybernetics (IEEE SMC)
        caption: 2024
        description: |
          This paper presents a novel approach to mitigating hallucinations in large language models through a technique called Curative Prompt Refinement (CPR). 
          The research was accepted for publication at the IEEE International Conference on Systems, Man, and Cybernetics (IEEE SMC) in 2024.
    
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Research Projects
        description: | 
          **LLM Development for Chemical Control Systems**  
          *Agency for Defense Development (ADD), Korea*  
          **Role:** Researcher  
          **Period:** Oct 2023 - Jan 2024  
          - Developed a large language model (LLM) for chemical control systems.
          - Contributed significantly to the AI capabilities in the defense sector.

          **LLM Assistant for Elementary School Teachers**  
          *I-Scream Education, Korea*  
          **Role:** Researcher  
          **Period:** May 2023 - Nov 2023  
          - Fine-tuned the Polyglot-kr model to assist elementary school teachers.
          - Adjusted the model's tone to be appropriate for young learners.

      - layout: top-middle
        title: Engineering Projects
        description: |
          **KakaoPay API Payments System**  
          *Mobile Entropy, Korea*  
          **Role:** Backend Engineer  
          **Period:** May 2022 - Jan 2023  
          - Set up and integrated the KakaoPay API for gas bill payments, streamlining the payment process for users.
          - Ensured secure and efficient processing of payments through the KakaoPay platform.

          **System Monitoring with Prometheus and Grafana**  
          *Mobile Entropy, Korea*  
          **Role:** Backend Engineer  
          **Period:** May 2022 - Jan 2023  
          - Developed and deployed a comprehensive system monitoring solution using Prometheus and Grafana.
          - Monitored the company’s services hosted on Naver Cloud, improving operational reliability and performance.

          **Giro Payment Service using Open API**  
          *Mobile Entropy, Korea*  
          **Role:** Frontend Engineer  
          **Period:** Jan 2022 - Apr 2022  
          - Developed frontend interfaces and integrated Open API for secure payments.
          - Contributed to the enhancement of fintech solutions.

          **IoT Smart Safety System**  
          *Mobile Entropy, Korea*  
          **Role:** Frontend Developer & IoT Logic Developer  
          **Period:** Jun 2021 - Dec 2021  
          - Developed IoT manipulation logic and frontend interfaces for workplace safety.
          - Improved safety standards with smart IoT solutions.

      - layout: top-middle
        title: Academic Projects
        description: |
          **Improving the Argus-SAF Tool**  
          *Chungnam National University, Korea*  
          **Role:** Researcher  
          **Period:** Feb 2020 - Nov 2020  
          - Enhanced an APK analysis tool for mitigating malware risks in Android applications.

          **Predicting Sexual Orientation Using Survey Data**  
          *Chungnam National University, Korea*  
          **Role:** Student Researcher  
          **Period:** Sep 2020 - Dec 2020  
          - Applied machine learning techniques to analyze social science survey data.

          **Predicting the Probability of Winning in League of Legends**  
          *Chungnam National University, Korea*  
          **Role:** Student Researcher  
          **Period:** Mar 2020 - Jun 2020  
          - Developed a model to predict match outcomes based on draft picks using data analysis and machine learning.

  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mobile Entropy
        link: 
        sub_title: Backend Engineer
        caption: May 2022 - Jan 2023
        quote: >
          Spearheaded the integration of critical backend systems for payment processing and system monitoring.
        description: | # this will include new lines to allow paragraphs
            - Set up and integrated the KakaoPay API for gas bill payments, improving payment processing efficiency.
            - Developed and deployed a monitoring solution using Prometheus and Grafana, enhancing system reliability for services hosted on Naver Cloud.

      - layout: left
        title: Mobile Entropy
        link: 
        # link_text: boringcompany.com
        sub_title: Frontend Engineer
        caption: Jun 2021 - Apr 2022
        quote: >
          Played a key role in developing a secure Giro payment service using Open API.
          Worked on enhancing IoT-based smart safety systems.
        description: | # this will include new lines to allow paragraphs
            - Developed frontend interfaces and integrated APIs for the Giro payment service, contributing to a seamless user experience.
            - Focused on the development of IoT logic and frontend interfaces for smart safety systems, improving workplace safety and efficiency.

      - layout: left
        title: Chungnam National University
        link: 
        # link_text: boringcompany.com
        sub_title: Researcher
        caption: Feb 2020 - Nov 2020
        quote: >
          Contributed to reducing risks associated with Android APKs.
        description: | # this will include new lines to allow paragraphs
            Improved the Argus-SAF tool for APK analysis, focusing on malignity mitigation, which provided better security for Android applications.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Korea University
        caption: Feb 2023 - Present
        sub_title: MSc Artificial Intelligence
        quote: >
          Research focused on mitigating large language model hallucinations.
        description: | # this will include new lines to allow paragraphs
          Currently pursuing a Master's degree in Artificial Intelligence with a focus on large language models and prompt refinement techniques under the guidance of Professor Seong Whan Lee. GPA: 4.25 / 4.5

      - layout: left
        title: Chungnam National University
        caption: Mar 2015 - Feb 2021
        sub_title: BSc Computer Science
        quote: >
          Thesis on Developing Safe UI for Android OS.
        description: | # this will include new lines to allow paragraphs
          Completed a Bachelor's degree in Computer Science with a thesis on UI safety in Android OS. Developed strong foundational skills in computer science and programming. GPA: 3.18 / 4.5

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my academic and professional interests, I have a number of hobbies and passions:
      - Rock climbing
      - Gaming
      - Exploring new technologies
      - [Learning new skills](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Here is an interesting image  
      ![Trees](/images/landscape-trees.jpg "Trees")


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
